// Build audits/20260505/summary.md from raw JSON outputs.
// Reads:  lighthouse-{slug}-{mobile|desktop|tap-targets}.json
//         axe-{slug}.json
//         tap-targets-44x44-{slug}.json
// Writes: summary.md (overwrites)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DIR = __dirname;

const PAGES = [
  ['home',                                       'https://aoyama-nogizaka.com/'],
  ['team',                                       'https://aoyama-nogizaka.com/team'],
  ['news',                                       'https://aoyama-nogizaka.com/news/'],
  ['privacy',                                    'https://aoyama-nogizaka.com/privacy'],
  ['activist-dashboard',                         'https://aoyama-nogizaka.com/activist-dashboard.html'],
  ['risk-assessment',                            'https://aoyama-nogizaka.com/risk-assessment.html'],
  ['activist-screener',                          'https://aoyama-nogizaka.com/activist-screener.html'],
  ['food-service',                               'https://aoyama-nogizaka.com/food-service.html'],
  ['saas',                                       'https://aoyama-nogizaka.com/saas.html'],
  ['ad-agency',                                  'https://aoyama-nogizaka.com/ad-agency.html'],
  ['digital-media',                              'https://aoyama-nogizaka.com/digital-media.html'],
  ['entertainment-sector-dashboard',             'https://aoyama-nogizaka.com/entertainment-sector-dashboard.html'],
  ['news-activist-shareholder-proposals-japan',  'https://aoyama-nogizaka.com/news/activist-shareholder-proposals-japan.html'],
];

// 4/21 baseline values (hardcoded from audits/20260421/lighthouse-mobile/summary.md and axe/summary.md)
const BASE_4_21 = {
  // [perf, a11y, bp, seo, axe-nodes]
  'home':                                       [56, 90, 96, 100, 4],
  'team':                                       [87, 91, 96, 100, 24],
  'news':                                       [82, 91, 92, 100, 19],
  'privacy':                                    [56, 91, 96, 100, 17],
  'activist-dashboard':                         [60, 87, 96, 100, 221],
  'risk-assessment':                            [73, 86, 96, 100, 49],
  'activist-screener':                          [72, 92, 96, 100, 27],
  'food-service':                               [77, 88, 96, 100, 25],
  'saas':                                       [78, 88, 96, 100, 22],
  'ad-agency':                                  [83, 88, 96, 100, 23],
  'digital-media':                              [82, 88, 96, 100, 22],
  'entertainment-sector-dashboard':             [78, 88, 96, 100, 19],
  'news-activist-shareholder-proposals-japan':  [54, 94, 92, 100, 126],
};

const readJSON = (p) => JSON.parse(fs.readFileSync(p, 'utf-8'));

function lhScores(file) {
  const j = readJSON(file);
  const c = j.categories || {};
  const get = (k) => {
    const v = c[k]?.score;
    return v == null ? null : Math.round(v * 100);
  };
  return {
    perf: get('performance'),
    a11y: get('accessibility'),
    bp:   get('best-practices'),
    seo:  get('seo'),
  };
}

function lhTargetSize(file) {
  const j = readJSON(file);
  const items = j.audits?.['target-size']?.details?.items;
  return Array.isArray(items) ? items.length : null;
}

function axeStats(file) {
  const j = readJSON(file);
  const arr = Array.isArray(j) ? j : [j];
  const first = arr[0] || {};
  const violations = first.violations || [];
  const nodes = violations.reduce((s, v) => s + ((v.nodes || []).length), 0);
  return { rules: violations.length, nodes };
}

function tap44(file) {
  const j = readJSON(file);
  return j.total ?? null;
}

function fmt(n) { return n == null ? '—' : String(n); }
function diff(a, b) {
  if (a == null || b == null) return '—';
  const d = a - b;
  if (d === 0) return '±0';
  return (d > 0 ? '+' : '') + d;
}

const rows = [];
for (const [slug, url] of PAGES) {
  const m = lhScores(path.join(DIR, `lighthouse-${slug}-mobile.json`));
  const d = lhScores(path.join(DIR, `lighthouse-${slug}-desktop.json`));
  const ts = lhTargetSize(path.join(DIR, `lighthouse-${slug}-tap-targets.json`));
  const ax = axeStats(path.join(DIR, `axe-${slug}.json`));
  const t44 = tap44(path.join(DIR, `tap-targets-44x44-${slug}.json`));
  const base = BASE_4_21[slug] || [null, null, null, null, null];
  rows.push({ slug, url, m, d, ts, ax, t44, base });
}

// === Markdown ===
let md = '';
md += `# Baseline Audit — 2026-05-05\n\n`;
md += `Lighthouse v13.2.0 (mobile + desktop + tap-targets) / @axe-core/cli v4.11.3 / Playwright (44×44 enhanced).\n`;
md += `Generated by: \`audits/20260505/build-summary.mjs\`.\n\n`;

md += `## Matrix (page × LH scores + tap-target violations + axe)\n\n`;
md += `Diff columns: 5/5 − 4/21. positive = improvement (perf/a11y up; axe nodes down → "+" means fewer nodes today).\n\n`;
md += `| page | mobile-perf | desktop-perf | a11y | best-practices | seo | target-size violations (24×24 AA) | 44×44 violations (Playwright, 2.5.5) | axe rules | axe nodes | Δperf-mobile | Δa11y | Δaxe-nodes |\n`;
md += `|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n`;

for (const r of rows) {
  const slugLink = `[${r.slug}](${r.url})`;
  const bp = r.base;
  const dPerf  = diff(r.m.perf, bp[0]);
  const dA11y  = diff(r.m.a11y, bp[1]);
  // axe-nodes: today smaller is better, so present diff as (today - 4/21) raw
  const dNodes = diff(r.ax.nodes, bp[4]);
  md += `| ${slugLink} | ${fmt(r.m.perf)} | ${fmt(r.d.perf)} | ${fmt(r.m.a11y)} | ${fmt(r.m.bp)} | ${fmt(r.m.seo)} | ${fmt(r.ts)} | ${fmt(r.t44)} | ${fmt(r.ax.rules)} | ${fmt(r.ax.nodes)} | ${dPerf} | ${dA11y} | ${dNodes} |\n`;
}

// Aggregates
const avg = (xs) => xs.length ? Math.round(xs.reduce((a,b) => a+b, 0) / xs.length * 10) / 10 : null;
const sum = (xs) => xs.reduce((a,b) => a+b, 0);
const mPerfs = rows.map(r => r.m.perf);
const dPerfs = rows.map(r => r.d.perf);
const a11ys  = rows.map(r => r.m.a11y);
const bps    = rows.map(r => r.m.bp);
const seos   = rows.map(r => r.m.seo);
const tss    = rows.map(r => r.ts).filter(x => x != null);
const t44s   = rows.map(r => r.t44);
const axNodes= rows.map(r => r.ax.nodes);

const base_mPerf = avg(rows.map(r => r.base[0]));
const base_a11y  = avg(rows.map(r => r.base[1]));
const base_axe   = sum(rows.map(r => r.base[4]));

md += `\n## Aggregates\n\n`;
md += `| metric | 5/5 (today) | 4/21 (baseline) | Δ |\n|---|---:|---:|---:|\n`;
md += `| mobile-perf avg | ${avg(mPerfs)} | ${base_mPerf} | ${(avg(mPerfs) - base_mPerf).toFixed(1)} |\n`;
md += `| desktop-perf avg | ${avg(dPerfs)} | — | — |\n`;
md += `| a11y avg | ${avg(a11ys)} | ${base_a11y} | ${(avg(a11ys) - base_a11y).toFixed(1)} |\n`;
md += `| best-practices avg | ${avg(bps)} | — | — |\n`;
md += `| seo avg | ${avg(seos)} | — | — |\n`;
md += `| target-size violations sum (24×24) | ${sum(tss)} | — | — |\n`;
md += `| 44×44 violations sum (Playwright) | ${sum(t44s)} | — | — |\n`;
md += `| axe nodes total | ${sum(axNodes)} | ${base_axe} | ${sum(axNodes) - base_axe} |\n`;

// Worst pages
const sortedByPerf = [...rows].sort((a, b) => a.m.perf - b.m.perf);
md += `\n## Top 3 worst by mobile-perf\n\n`;
md += `| rank | page | mobile-perf | 4/21 | Δ |\n|---:|---|---:|---:|---:|\n`;
for (let i = 0; i < 3 && i < sortedByPerf.length; i++) {
  const r = sortedByPerf[i];
  md += `| ${i+1} | ${r.slug} | ${r.m.perf} | ${r.base[0]} | ${diff(r.m.perf, r.base[0])} |\n`;
}

const sortedBy44 = [...rows].sort((a, b) => b.t44 - a.t44);
md += `\n## Top 3 worst by 44×44 violations\n\n`;
md += `| rank | page | 44×44 violations |\n|---:|---|---:|\n`;
for (let i = 0; i < 3 && i < sortedBy44.length; i++) {
  const r = sortedBy44[i];
  md += `| ${i+1} | ${r.slug} | ${r.t44} |\n`;
}

md += `\n## 本日 audit の方法論\n\n`;
md += `### Lighthouse\n`;
md += `- Version: **13.2.0** (npx --yes lighthouse, npm cache 経由)\n`;
md += `- 共通フラグ: \`--output=json --chrome-flags="--headless --no-sandbox" --quiet --max-wait-for-load=60000\`\n`;
md += `- mobile: \`--form-factor=mobile\`\n`;
md += `- desktop: \`--preset=desktop\`\n`;
md += `- tap-targets ファイル: \`--form-factor=mobile --only-audits=tap-targets,target-size\`\n`;
md += `  - **Lighthouse 13.x で \`tap-targets\` audit は削除済み**。実際に出力される audit は \`target-size\` のみで、これは axe-core \`target-size\` ルール委譲、**WCAG 2.5.8 Level AA = 24×24 CSS px** 判定。\n`;
md += `  - 表の "target-size violations (24×24 AA)" 列は \`audits.target-size.details.items.length\`。\n`;
md += `- Chrome kill 例外について: 全 LH 実行で \`chrome-launcher\` の \`Launcher.kill\` がスタックトレースに出るが、JSON は完全に書き出され全カテゴリスコアが取得できている。Windows + LH13 + headless Chrome の既知の terminate ノイズと判断、続行に支障なし。\n\n`;

md += `### Playwright (44×44 enhanced)\n`;
md += `- WCAG 2.5.5 Level AAA 相当 (44×44 CSS px) の独立計測。LH 13.x では拾えないため別ジョブで補完。\n`;
md += `- Viewport: 375×667 (iPhone SE), Chromium headless\n`;
md += `- 対象セレクタ: \`a, button, input[type=button|submit|reset], [role=button], [role=link], [onclick], label[for]\`\n`;
md += `- 除外: display:none / visibility:hidden,collapse / opacity:0 / 0×0 矩形\n`;
md += `- 計測スクリプト: 4/21 baseline の \`audits/measure-tap-targets.js\` を作業ツリーに取得し、PAGES に 13 番目の URL 追加 + 出力を slug 別 JSON 化する最小編集を施し実行。スクリプト自体は本 commit に含めず、実行後に作業ツリーから削除。\n`;
md += `- per-page JSON: \`tap-targets-44x44-{slug}.json\`（各 URL の violations 配列、deficit、selector path 等を保存）\n\n`;

md += `### axe-core CLI\n`;
md += `- Version: **4.11.3** (npx --yes @axe-core/cli)\n`;
md += `- WCAG 2.1 / 2.2 AA 相当のルールセットで headless Chrome 実行\n`;
md += `- 表の "axe rules" = violations 配列の長さ (該当ルール数)、"axe nodes" = 全 violations の nodes を合算 (4/21 summary と同手法)\n\n`;

md += `### 4/21 vs 5/5 の限界\n`;
md += `- 4/21 は LH **mobile only**（desktop は無し）のため desktop-perf の Δ は計算不可。\n`;
md += `- 4/21 は target-size / 44×44 専用測定が baseline summary に含まれていなかったため、これらの Δ も省略。\n`;
md += `- axe nodes の差分は 4/21 と同じカウント方法 (rule × node) で計算。\n\n`;

md += `### Raw outputs\n`;
md += `- LH JSON × 39 (13 ページ × {mobile, desktop, tap-targets})\n`;
md += `- axe JSON × 13\n`;
md += `- 44×44 JSON × 13\n`;
md += `- ログ: \`_dry-run.log\`, \`_run.log\`, \`_playwright-44x44.log\`\n`;

const outPath = path.join(DIR, 'summary.md');
fs.writeFileSync(outPath, md);
console.log('WROTE:', outPath, `(${md.length} bytes, ${rows.length} pages)`);
